config/routes.rb
Kc045::Application.routes.draw do


  namespace :settings do
    resource :profile, :only => [:show, :edit, :update, :destroy]
    resource :talk, :only => [:show, :edit, :update]
  end

  root :to => "welcome#index"

  resources "members", :only => [:index, :show]
  resource :timetable, :only => :show
  match '/auth/:provider/callback', :to => "sessions#callback"
  match '/logout', :to => "sessions#destroy"

end

app/models/talk.rb
class Talk < ActiveRecord::Base
  attr_accessible :title, :slide

  belongs_to :user

  validates :title, :presence => true, :length => {:maximum => 200}
end

app/controllers/settings/profiles_controller.rb
class Settings::ProfilesController < ApplicationController
  before_filter :login_required
  before_filter :set_resource

  def show
  end

  def edit
  end

  def update
    if @profile.update_attributes(params[:profile])
      redirect_to(:action => :show)
    else
      flash.now[:errors] = @profile.errors.full_messages
      render :action => "edit"
    end
  end

  def destroy
    session[:user_id] = nil
    current_user.destroy

    redirect_to root_path, :flash => {:notice => I18n.t("settings.profiles.destroyed")}
  end


  private
    def set_resource
      @profile = current_user.profile
    end
end

app/controllers/settings/talks_controller.rb
class Settings::TalksController < ApplicationController
  before_filter :login_required
  before_filter :set_resource

  def show
  end

  def edit
  end

  def update
    if @talk.update_attributes(params[:talk])
      redirect_to(:action => :show)
    else
      flash.now[:errors] = @talk.errors.full_messages
      render :action => "edit"
    end
  end


  private
    def set_resource
      @talk = current_user.talk
    end
end

app/helpers/settings/profiles_helper.rb
module Settings::ProfilesHelper
end

app/helpers/settings/talks_helper.rb
module Settings::TalksHelper
end

app/views/settings/talks/_form.html.haml
%fieldset
  %legend
  .control-group
    = f.label :title, t(".title"), :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :slide, t(".slide"), :class => 'control-label'
    .controls
      = f.text_field :slide, :class => 'text_field'
  .form-actions
    = f.submit t("common.update"), :class => 'btn btn-primary'
    = link_to t("common.cancel"), settings_talk_path, :class => 'btn'

app/views/settings/talks/edit.html.haml
= form_for [:settings, @talk], :url => settings_talk_path, :html => { :class => "edit_talk form-horizontal", :id => "edit_talk" } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/settings/talks/show.html.haml
%label{:class => "label"}= t(".title") + ":"
%p= @talk.title
%label{:class => "label"}= t(".slide") + ":"
%p= @talk.slide

.form-actions
  = link_to t("common.edit"), edit_settings_talk_path, :class => 'btn btn-primary'