config/routes.rb
Kc045::Application.routes.draw do


  namespace :settings do
    resource :profile, :only => [:show, :edit, :update, :destroy]
    resource :talk, :only => [:show, :edit, :update]
  end

  root :to => "welcome#index"

  resources "members", :only => [:index, :show]
  resource :timetable, :only => :show
  match '/auth/:provider/callback', :to => "sessions#callback"
  match '/logout', :to => "sessions#destroy"

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  include Enumerize

  belongs_to :user

  attr_accessible :name, :phonetic_name, :blog, :hometown, :comment, :age, :attend_parties

  validates :name, :presence => true, :length => {:maximum => 60}
  validates :phonetic_name, :length => {:maximum => 60}
  validates :blog, :length => {:maximum => 200}
  validates :comment, :length => {:maximum => 140}
  validates :age, :numericality => {:only_integer => true, :allow_blank => true}

  scope :is_attend_party, where(:attend_parties => true)


  enumerize :hometown, :in => [
                               :secret,
                               :hokkaido,
                               :aomori,
                               :iwate,
                               :miyagi,
                               :akita,
                               :yamagata,
                               :fukushima,
                               :ibaraki,
                               :tochigi,
                               :gunma,
                               :saitama,
                               :chiba,
                               :tokyo,
                               :kanagawa,
                               :niigata,
                               :toyama,
                               :ishikawa,
                               :fukui,
                               :yamanashi,
                               :nagano,
                               :gifu,
                               :shizuoka,
                               :aichi,
                               :mie,
                               :shiga,
                               :kyoto,
                               :osaka,
                               :hyogo,
                               :nara,
                               :wakayama,
                               :tottori,
                               :shimane,
                               :okayama,
                               :hiroshima,
                               :yamaguchi,
                               :tokushima,
                               :kagawa,
                               :ehime,
                               :kochi,
                               :fukuoka,
                               :saga,
                               :nagasaki,
                               :kumamoto,
                               :oita,
                               :miyazaki,
                               :kagoshima,
                               :okinawa
                              ], :default => :secret

end

app/controllers/settings/profiles_controller.rb
class Settings::ProfilesController < ApplicationController
  before_filter :login_required
  before_filter :set_resource

  def show
  end

  def edit
  end

  def update
    if @profile.update_attributes(params[:profile])
      redirect_to(:action => :show)
    else
      flash.now[:errors] = @profile.errors.full_messages
      render :action => "edit"
    end
  end

  def destroy
    session[:user_id] = nil
    current_user.destroy

    redirect_to root_path, :flash => {:notice => I18n.t("settings.profiles.destroyed")}
  end


  private
    def set_resource
      @profile = current_user.profile
    end
end

app/controllers/settings/talks_controller.rb
class Settings::TalksController < ApplicationController
  before_filter :login_required
  before_filter :set_resource

  def show
  end

  def edit
  end

  def update
    if @talk.update_attributes(params[:talk])
      redirect_to(:action => :show)
    else
      flash.now[:errors] = @talk.errors.full_messages
      render :action => "edit"
    end
  end


  private
    def set_resource
      @talk = current_user.talk
    end
end

app/helpers/settings/profiles_helper.rb
module Settings::ProfilesHelper
end

app/helpers/settings/talks_helper.rb
module Settings::TalksHelper
end

app/views/settings/profiles/_form.html.haml
%fieldset
  %legend
  .control-group
    = f.label :name, t(".name"), :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :phonetic_name, t(".phonetic_name"), :class => 'control-label'
    .controls
      = f.text_field :phonetic_name, :class => 'text_field'
  .control-group
    = f.label :age, t(".age"), :class => 'control-label'
    .controls
      = f.text_field :age, :class => 'text_field'
  .control-group
    = f.label :hometown, t(".hometown"), :class => 'control-label'
    .controls
      = f.select :hometown, Profile.hometown.options
  .control-group
    = f.label :blog, t(".blog"), :class => 'control-label'
    .controls
      = f.text_field :blog, :class => 'text_field'
  .control-group
    = f.label :attend_parties, t(".attend_parties"), :class => 'control-label'
    .controls
      %label.radio.inline
        = f.radio_button :attend_parties, true
        = t(".attend")
      %label.radio.inline
        = f.radio_button :attend_parties, false
        = t(".not_to_attend")
  .control-group
    = f.label :comment, t(".comment"), :class => 'control-label'
    .controls
      = f.text_field :comment, :class => 'text_area'
  .form-actions
    = f.submit t("common.update"), :class => 'btn btn-primary'
    = link_to t("common.cancel"), settings_profile_path, :class => 'btn'

app/views/settings/profiles/edit.html.haml
= form_for @profile, :url => settings_profile_path, :html => { :class => "edit_profile form-horizontal", :id => "edit_profile" } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/settings/profiles/show.html.haml
.row
  .span1
    = image_tag @profile.user.image
  .span6
    %label= @profile.name
    = link_to(@profile.user.talk.title, settings_talk_path)
  .span2

.row
  .span9
    %label{:class => "label"}= t(".phonetic_name") + ":"
    %p= @profile.phonetic_name
    %label{:class => "label"}= t(".age") + ":"
    %p= @profile.age
    %label{:class => "label"}= t(".hometown") + ":"
    %p= @profile.hometown.text
    %label{:class => "label"}= t(".attend_parties") + ":"
    %p= @profile.attend_parties? ? t(".attend") : t(".not_to_attend")
    %label{:class => "label"}= t(".blog") + ":"
    %p= @profile.blog
    %label{:class => "label"}= t(".comment") + ":"
    %p= @profile.comment

    .form-actions
      = link_to t("common.edit"), edit_settings_profile_path, :class => 'btn btn-primary'
      = link_to t("common.participation_cancel"), settings_profile_path, :method => :delete, :class => 'btn btn-danger', :confirm => t(".confirm")