config/routes.rb
Kc045::Application.routes.draw do


  namespace :settings do
    resource :profile, :only => [:show, :edit, :update, :destroy]
    resource :talk, :only => [:show, :edit, :update]
  end

  root :to => "welcome#index"

  resources "members", :only => [:index, :show]
  resource :timetable, :only => :show
  match '/auth/:provider/callback', :to => "sessions#callback"
  match '/logout', :to => "sessions#destroy"

end

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : t("application_name")
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    / Le styles
    = stylesheet_link_tag "application", :media => "all"
    / Le fav and touch icons
    %link{:href => "/favicon.ico", :rel => "shortcut icon"}/
    -# %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    -# %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    -# %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"}= t("application_name")
          .container-fluid.nav-collapse
            = tabs
            %ul.nav.secondary-nav
              - if signed_in?
                %li.avater.dropdown
                  %a.avater.dropdown-toggle{:data => {:toggle => "dropdown"}, :href => "#"}
                    = image_tag current_user.image, :title => current_user.name
                    = current_user.screen_name
                  %ul.dropdown-menu
                    %li.leaf= link_to t("common.header.setting"), settings_profile_path
                    %li.leaf= link_to t("common.header.talk"), settings_talk_path
                    %li.leaf= link_to t("common.header.logout"), logout_path
              - else
                %li= link_to t("common.header.login"), '/auth/twitter'

    .container
      .content
        .row
          .span9
            = render "shared/flash_area"
            = yield
          .span3
            = render "shared/countdown"
            = render "shared/participant_count"
            = render "shared/party"
            = render "shared/link"
      %footer= footer
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"