config/routes.rb
Kc045::Application.routes.draw do


  namespace :settings do
    resource :profile, :only => [:show, :edit, :update, :destroy]
    resource :talk, :only => [:show, :edit, :update]
  end

  root :to => "welcome#index"

  resources "members", :only => [:index, :show]
  resource :timetable, :only => :show
  match '/auth/:provider/callback', :to => "sessions#callback"
  match '/logout', :to => "sessions#destroy"

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = User.all
  end

  def show
    @member = User.find(params[:id])
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/index.html.haml
%h1= t(".header")
%table#members_table.table.table-striped
  %thead
    %tr
      %th.image_col
      %th= t(".name")
      %th= t(".comment")
      %th= t(".attend_parties")
      -# %th= t(".registered_at")
  %tbody
    - @members.each do |member|
      %tr
        %td.image_col= image_tag member.image
        %td= link_to member.screen_name, member_path(member.id)
        %td= member.profile.comment
        %td= member.profile.attend_parties? ? "○" : nil
        -# %td= I18n.l member.created_at, :format => :short

app/views/members/show.html.haml
.row
  .span1
    = image_tag @member.image
  .span6
    = @member.display_name
  .span2
    = raw follow_button(@member.screen_name)

.row
  .span9
    %label.label= t(".talk_title") + ":"
    %p= @member.talk.title
    %label{:class => "label"}= t(".comment") + ":"
    = @member.profile.comment
    %label{:class => "label"}= t(".age") + ":"
    %p= @member.profile.age
    %label{:class => "label"}= t(".hometown") + ":"
    %p= @member.profile.hometown.text
    %label{:class => "label"}= t(".attend_parties") + ":"
    %p= @member.profile.attend_parties? ? t(".attend") : t(".not_to_attend")
    %label{:class => "label"}= t(".blog") + ":"
    %p= @member.profile.blog